### PR TITLE
feat (SafariDebug) Continously reopens debugger windows opened from t…

### PR DESCRIPTION
**Pull request by matti**
Safari debug windows opened from the terminal with "sd" are kept open until steroids is closed. This enables users to automatically resume debugging when the code is reloaded.

Also when the Safari crashes during the reload the window is opened after crash is acknowledged. Automatic acknowledgement is left as future work.

This introduces a global interval that blindly checks for window titles every 3 seconds. Yes it's a horrible thing to do.

### CODE REVIEW

**Comment by matti** [comment]
It's intentional that debug views opened from the GUI don't reopen.

**Comment by Leeds-eBooks** [comment]
@matti why?

**Comment by matti** [comment]
@Leeds-eBooks to "fix" issue where Safari keeps crashing when the WebView disappears (from code reload). Also to keep debugger "attached" to the view if needed.

Before merging should have --keep-debugger-open option

What do you think?

**Comment by Leeds-eBooks** [comment]
@matti Ah ok I see. Is `--keep-debugger-open` available now or are you asking me if I think it's a good idea?

**Comment by matti** [comment]
No, not yet.  I was asking if my explanation + feature makes sense :)

**Comment by Leeds-eBooks** [comment]
@matti Cool :) well not having to manually reopen debug windows would be great. I've never tried opening from terminal because I assumed I had to type the full address to the page. Is this an incorrect assumption?

**Comment by matti** [comment]
It does simple matching, so you can say "sd wel" to match "welcome.html"


On Mon, Aug 10, 2015 at 5:33 PM, Ben Styles <notifications@github.com>
wrote:

> @matti <https://github.com/matti> Cool :) well not having to manually
> reopen debug windows would be great. I've never tried opening from terminal
> because I assumed I had to type the full address to the page. Is this an
> incorrect assumption?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AppGyver/steroids/pull/1012#issuecomment-129475815>.
>



-- 
Matti Paksula, CTO // Tel: +1 (518) 966-2884, Skype: mattipaksula

AppGyver Inc.
RocketSpace, 225 Bush St, San Francisco, CA 94104, USA

**Comment by Leeds-eBooks** [comment]
@matti Nice. I should have tried this out. Will probably be using this all the time from now on. Thanks!

**Pull request closed without merging**
